# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 900)
        MainWindow.setStyleSheet("background-color: rgb(76, 76, 76);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(76, 76, 76);\n"
"color:white;\n"
"font:18px simHei;\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setToolTipDuration(-1)
        self.tabWidget.setStyleSheet("QTabBar::tab{background-color:rgb(76, 76, 76);}\n"
"QTabBar::tab:selected{color:red;background-color:rbg(255,200,255);}\n"
"\n"
"QTabWidget::pane\n"
"{\n"
"    border: -1px;\n"
"    \n"
"    left: 1px;\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setStyleSheet("")
        self.tab.setObjectName("tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(9)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_6.setStyleSheet("")
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.gridLayout_4.addWidget(self.groupBox_6, 1, 1, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox_5.setStyleSheet("border:none")
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_10.setContentsMargins(0, 0, -1, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.verticalLayout_10.addWidget(self.label)
        self.line_7 = QtWidgets.QFrame(self.groupBox_5)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_10.addWidget(self.line_7)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_1 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_1.sizePolicy().hasHeightForWidth())
        self.label_1.setSizePolicy(sizePolicy)
        self.label_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_1.setAutoFillBackground(False)
        self.label_1.setTextFormat(QtCore.Qt.AutoText)
        self.label_1.setScaledContents(False)
        self.label_1.setWordWrap(False)
        self.label_1.setObjectName("label_1")
        self.verticalLayout_9.addWidget(self.label_1)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(160, 0))
        self.lineEdit.setStyleSheet("border:2px groove gray;\n"
"border-radius:10px;\n"
"background-color: rgb(255, 255, 255);\n"
"color:black")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_9.addWidget(self.lineEdit)
        self.line = QtWidgets.QFrame(self.groupBox_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_9.addWidget(self.line)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(150, 0))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_9.addWidget(self.label_2)
        self.StartDataEdit = QtWidgets.QDateEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartDataEdit.sizePolicy().hasHeightForWidth())
        self.StartDataEdit.setSizePolicy(sizePolicy)
        self.StartDataEdit.setMinimumSize(QtCore.QSize(160, 0))
        self.StartDataEdit.setMaximumSize(QtCore.QSize(204, 16777215))
        self.StartDataEdit.setStyleSheet("border:2px groove gray;\n"
"\n"
"border-radius:10px;\n"
"alternate-background-color: rgb(85, 255, 127);\n"
"\n"
"\n"
"\n"
"font: 11pt simHei;\n"
"\n"
"")
        self.StartDataEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2017, 9, 14), QtCore.QTime(0, 0, 0)))
        self.StartDataEdit.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2021, 3, 31), QtCore.QTime(23, 59, 59)))
        self.StartDataEdit.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2010, 9, 14), QtCore.QTime(0, 0, 0)))
        self.StartDataEdit.setObjectName("StartDataEdit")
        self.verticalLayout_9.addWidget(self.StartDataEdit)
        self.EndDataEdit = QtWidgets.QDateEdit(self.groupBox_2)
        self.EndDataEdit.setMinimumSize(QtCore.QSize(160, 0))
        self.EndDataEdit.setStyleSheet("border:2px groove gray;\n"
"\n"
"border-radius:10px;\n"
"alternate-background-color: rgb(85, 255, 127);\n"
"\n"
"\n"
"\n"
"font: 11pt simHei;\n"
"")
        self.EndDataEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 9, 14), QtCore.QTime(0, 0, 0)))
        self.EndDataEdit.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2021, 3, 31), QtCore.QTime(23, 59, 59)))
        self.EndDataEdit.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2010, 9, 14), QtCore.QTime(0, 0, 0)))
        self.EndDataEdit.setObjectName("EndDataEdit")
        self.verticalLayout_9.addWidget(self.EndDataEdit)
        self.verticalLayout_10.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_3.setStyleSheet("border:none")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_10.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.Selectbtn = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Selectbtn.sizePolicy().hasHeightForWidth())
        self.Selectbtn.setSizePolicy(sizePolicy)
        self.Selectbtn.setStyleSheet("border:2px groove gray;\n"
"\n"
"border-radius:10px;\n"
"width:90;\n"
"height:25")
        self.Selectbtn.setObjectName("Selectbtn")
        self.horizontalLayout_10.addWidget(self.Selectbtn)
        spacerItem = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.verticalLayout_10.addWidget(self.groupBox_3)
        self.chkBox_jincha = QtWidgets.QRadioButton(self.groupBox_5)
        self.chkBox_jincha.setStyleSheet("")
        self.chkBox_jincha.setObjectName("chkBox_jincha")
        self.verticalLayout_10.addWidget(self.chkBox_jincha)
        self.chkbox_sicha = QtWidgets.QRadioButton(self.groupBox_5)
        self.chkbox_sicha.setCheckable(True)
        self.chkbox_sicha.setObjectName("chkbox_sicha")
        self.verticalLayout_10.addWidget(self.chkbox_sicha)
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setMinimumSize(QtCore.QSize(150, 0))
        self.textEdit.setMaximumSize(QtCore.QSize(160, 16777215))
        self.textEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:2px groove gray;\n"
"border-radius:20px;\n"
"color:black")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_10.addWidget(self.textEdit)
        self.gridLayout_4.addWidget(self.groupBox_5, 1, 0, 2, 1)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.tabWidget_2.sizePolicy().hasHeightForWidth())
        self.tabWidget_2.setSizePolicy(sizePolicy)
        self.tabWidget_2.setStyleSheet("")
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget_2.addTab(self.tab_6, "")
        self.gridLayout_4.addWidget(self.tabWidget_2, 2, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setStyleSheet("border:none")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_9.setContentsMargins(11, 0, -1, -1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(138, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.ShangZhengbtn = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ShangZhengbtn.sizePolicy().hasHeightForWidth())
        self.ShangZhengbtn.setSizePolicy(sizePolicy)
        self.ShangZhengbtn.setStyleSheet("border:2px groove gray;\n"
"width:90;\n"
"height:25;\n"
"\n"
"")
        self.ShangZhengbtn.setCheckable(False)
        self.ShangZhengbtn.setChecked(False)
        self.ShangZhengbtn.setAutoRepeat(False)
        self.ShangZhengbtn.setAutoExclusive(False)
        self.ShangZhengbtn.setAutoDefault(False)
        self.ShangZhengbtn.setDefault(True)
        self.ShangZhengbtn.setFlat(False)
        self.ShangZhengbtn.setObjectName("ShangZhengbtn")
        self.horizontalLayout_9.addWidget(self.ShangZhengbtn)
        spacerItem3 = QtWidgets.QSpacerItem(58, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.ShenZhengbtn = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ShenZhengbtn.sizePolicy().hasHeightForWidth())
        self.ShenZhengbtn.setSizePolicy(sizePolicy)
        self.ShenZhengbtn.setStyleSheet("border:2px groove gray;\n"
"width:90;\n"
"height:25")
        self.ShenZhengbtn.setCheckable(False)
        self.ShenZhengbtn.setChecked(False)
        self.ShenZhengbtn.setAutoExclusive(False)
        self.ShenZhengbtn.setAutoDefault(False)
        self.ShenZhengbtn.setDefault(True)
        self.ShenZhengbtn.setFlat(False)
        self.ShenZhengbtn.setObjectName("ShenZhengbtn")
        self.horizontalLayout_9.addWidget(self.ShenZhengbtn)
        spacerItem4 = QtWidgets.QSpacerItem(58, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.HuShenbtn = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HuShenbtn.sizePolicy().hasHeightForWidth())
        self.HuShenbtn.setSizePolicy(sizePolicy)
        self.HuShenbtn.setStyleSheet("border:2px groove gray;\n"
"width:90;\n"
"height:25")
        self.HuShenbtn.setCheckable(False)
        self.HuShenbtn.setChecked(False)
        self.HuShenbtn.setAutoExclusive(False)
        self.HuShenbtn.setAutoDefault(False)
        self.HuShenbtn.setDefault(True)
        self.HuShenbtn.setFlat(False)
        self.HuShenbtn.setObjectName("HuShenbtn")
        self.horizontalLayout_9.addWidget(self.HuShenbtn)
        spacerItem5 = QtWidgets.QSpacerItem(138, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.groupBox_15 = QtWidgets.QGroupBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox_15.sizePolicy().hasHeightForWidth())
        self.groupBox_15.setSizePolicy(sizePolicy)
        self.groupBox_15.setStyleSheet("border:0px")
        self.groupBox_15.setTitle("")
        self.groupBox_15.setObjectName("groupBox_15")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_15)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem6 = QtWidgets.QSpacerItem(38, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.label_13 = QtWidgets.QLabel(self.groupBox_15)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_2.addWidget(self.label_13)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEdit_2.setStyleSheet("border:2px groove gray;\n"
"border-radius:10px;\n"
"background-color: rgb(255, 255, 255);\n"
"color:black")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.label_14 = QtWidgets.QLabel(self.groupBox_15)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_2.addWidget(self.label_14)
        self.StartDataEdit_2 = QtWidgets.QDateEdit(self.groupBox_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartDataEdit_2.sizePolicy().hasHeightForWidth())
        self.StartDataEdit_2.setSizePolicy(sizePolicy)
        self.StartDataEdit_2.setMinimumSize(QtCore.QSize(160, 0))
        self.StartDataEdit_2.setMaximumSize(QtCore.QSize(204, 16777215))
        self.StartDataEdit_2.setStyleSheet("border:2px groove gray;\n"
"\n"
"border-radius:10px;\n"
"alternate-background-color: rgb(85, 255, 127);\n"
"\n"
"\n"
"\n"
"font: 11pt simHei;\n"
"\n"
"")
        self.StartDataEdit_2.setDateTime(QtCore.QDateTime(QtCore.QDate(2017, 9, 14), QtCore.QTime(0, 0, 0)))
        self.StartDataEdit_2.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2021, 3, 31), QtCore.QTime(23, 59, 59)))
        self.StartDataEdit_2.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2010, 9, 14), QtCore.QTime(0, 0, 0)))
        self.StartDataEdit_2.setObjectName("StartDataEdit_2")
        self.horizontalLayout_2.addWidget(self.StartDataEdit_2)
        self.EndDataEdit_2 = QtWidgets.QDateEdit(self.groupBox_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EndDataEdit_2.sizePolicy().hasHeightForWidth())
        self.EndDataEdit_2.setSizePolicy(sizePolicy)
        self.EndDataEdit_2.setMinimumSize(QtCore.QSize(160, 0))
        self.EndDataEdit_2.setStyleSheet("border:2px groove gray;\n"
"\n"
"border-radius:10px;\n"
"alternate-background-color: rgb(85, 255, 127);\n"
"\n"
"\n"
"\n"
"font: 11pt simHei;\n"
"")
        self.EndDataEdit_2.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 9, 14), QtCore.QTime(0, 0, 0)))
        self.EndDataEdit_2.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2021, 3, 31), QtCore.QTime(23, 59, 59)))
        self.EndDataEdit_2.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2010, 9, 14), QtCore.QTime(0, 0, 0)))
        self.EndDataEdit_2.setObjectName("EndDataEdit_2")
        self.horizontalLayout_2.addWidget(self.EndDataEdit_2)
        self.Selectbtn_2 = QtWidgets.QPushButton(self.groupBox_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Selectbtn_2.sizePolicy().hasHeightForWidth())
        self.Selectbtn_2.setSizePolicy(sizePolicy)
        self.Selectbtn_2.setStyleSheet("border:2px groove gray;\n"
"\n"
"border-radius:10px;\n"
"width:90;\n"
"height:25")
        self.Selectbtn_2.setObjectName("Selectbtn_2")
        self.horizontalLayout_2.addWidget(self.Selectbtn_2)
        spacerItem7 = QtWidgets.QSpacerItem(38, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.verticalLayout_12.addWidget(self.groupBox_15)
        self.groupBox_16 = QtWidgets.QGroupBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(9)
        sizePolicy.setHeightForWidth(self.groupBox_16.sizePolicy().hasHeightForWidth())
        self.groupBox_16.setSizePolicy(sizePolicy)
        self.groupBox_16.setTitle("")
        self.groupBox_16.setObjectName("groupBox_16")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_16)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.tableView = QtWidgets.QTableView(self.groupBox_16)
        self.tableView.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"color:black")
        self.tableView.setObjectName("tableView")
        self.verticalLayout_13.addWidget(self.tableView)
        self.verticalLayout_12.addWidget(self.groupBox_16)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1014, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", " 参数输入"))
        self.label_1.setText(_translate("MainWindow", "股票代码"))
        self.label_2.setText(_translate("MainWindow", "时间(Start-End)"))
        self.StartDataEdit.setDisplayFormat(_translate("MainWindow", "yyyy-M-d"))
        self.EndDataEdit.setDisplayFormat(_translate("MainWindow", "yyyy-M-d"))
        self.Selectbtn.setText(_translate("MainWindow", "查找"))
        self.chkBox_jincha.setText(_translate("MainWindow", "金叉"))
        self.chkbox_sicha.setText(_translate("MainWindow", "死叉"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'simHei\'; font-size:18px; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:9pt;\"><br /></p></body></html>"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "MACD"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "RSI"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "KDJ"))
        self.ShangZhengbtn.setText(_translate("MainWindow", "上证指数"))
        self.ShenZhengbtn.setText(_translate("MainWindow", "深证成指"))
        self.HuShenbtn.setText(_translate("MainWindow", "沪深300"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "指标分析"))
        self.label_13.setText(_translate("MainWindow", "股票代码"))
        self.lineEdit_2.setText(_translate("MainWindow", ""))
        self.label_14.setText(_translate("MainWindow", "时间（Start-End）"))
        self.StartDataEdit_2.setDisplayFormat(_translate("MainWindow", "yyyy-M-d"))
        self.EndDataEdit_2.setDisplayFormat(_translate("MainWindow", "yyyy-M-d"))
        self.Selectbtn_2.setText(_translate("MainWindow", "查找"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "股票数据"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "股票回测"))
